# Generated by Django 5.2.3 on 2026-02-12 20:18

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=main.models.backup_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бэкап',
                'verbose_name_plural': 'Бэкапы',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=main.models.game_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата заказа')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist item',
                'verbose_name_plural': 'Wishlist items',
                'unique_together': {('user', 'product')},
            },
        ),
        # 🔹 ФУНКЦИИ
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION get_basket_count(p_user_id INT)
                RETURNS INT AS $$
                BEGIN
                    RETURN COALESCE((SELECT SUM(quantity) FROM main_basket WHERE user_id = p_user_id), 0);
                END;
                $$ LANGUAGE plpgsql;

                -- 2. Функция: количество элементов в желаемом у пользователя
                CREATE OR REPLACE FUNCTION get_wishlist_count(p_user_id INT)
                RETURNS INT AS $$
                BEGIN
                    RETURN COALESCE((SELECT COUNT(*) FROM main_wishlist WHERE user_id = p_user_id), 0);
                END;
                $$ LANGUAGE plpgsql;

                -- 3. Функция: сумма товаров в корзине пользователя
                CREATE OR REPLACE FUNCTION get_basket_total(p_user_id INT)
                RETURNS NUMERIC(10,2) AS $$
                BEGIN
                    RETURN COALESCE((
                        SELECT SUM(b.quantity * p.price)
                        FROM main_basket b
                        JOIN main_product p ON b.product_id = p.id
                        WHERE b.user_id = p_user_id
                    ), 0.00);
                END;
                $$ LANGUAGE plpgsql;
                """,
            reverse_sql="""
                DROP FUNCTION IF EXISTS get_basket_count(INT);
                DROP FUNCTION IF EXISTS get_wishlist_count(INT);
                DROP FUNCTION IF EXISTS get_basket_total(INT);
                """
        ),

        # 🔹 ТРИГГЕРЫ
        migrations.RunSQL(
            sql="""
                -- 1. Триггер: при установке discount → old_price = price, price = price * (1 - discount/100)
                CREATE OR REPLACE FUNCTION update_price_on_discount()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NEW.discount IS NOT NULL AND NEW.discount > 0 THEN
                        NEW.old_price := NEW.price;
                        NEW.price := ROUND(NEW.price * (100 - NEW.discount) / 100, 2);
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_update_price_on_discount
                BEFORE INSERT OR UPDATE OF discount ON main_product
                FOR EACH ROW
                EXECUTE FUNCTION update_price_on_discount();

                -- 2. Триггер: запретить добавление отзыва без покупки
                CREATE OR REPLACE FUNCTION prevent_review_without_purchase()
                RETURNS TRIGGER AS $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM main_orderitem oi
                        JOIN main_order o ON oi.order_id = o.id
                        WHERE oi.product_id = NEW.product_id
                          AND o.user_id = NEW.user_id
                    ) THEN
                        RAISE EXCEPTION 'Оставить отзыв можно только после покупки товара';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_prevent_fake_review
                BEFORE INSERT ON main_review
                FOR EACH ROW
                EXECUTE FUNCTION prevent_review_without_purchase();

                -- 3. Триггер: обновлять created_at при добавлении в корзину
                CREATE OR REPLACE FUNCTION set_basket_created_at_now()
                RETURNS TRIGGER AS $$
                BEGIN
                    NEW.created_at := NOW();
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER trg_set_basket_timestamp
                BEFORE INSERT ON main_basket
                FOR EACH ROW
                EXECUTE FUNCTION set_basket_created_at_now();
                """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS trg_update_price_on_discount ON main_product;
                DROP TRIGGER IF EXISTS trg_prevent_fake_review ON main_review;
                DROP TRIGGER IF EXISTS trg_set_basket_timestamp ON main_basket;
                DROP FUNCTION IF EXISTS update_price_on_discount();
                DROP FUNCTION IF EXISTS prevent_review_without_purchase();
                DROP FUNCTION IF EXISTS set_basket_created_at_now();
                """
        ),

        # 🔹 ПРОЦЕДУРЫ
        migrations.RunSQL(
            sql="""
                -- 1. Процедура: создать заказ из корзины
                CREATE OR REPLACE PROCEDURE create_order_from_basket(IN p_user_id INT)
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    v_count INT;
                    v_total DECIMAL(10,2) := 0;
                    v_new_order_id INT;
                BEGIN
                    -- Проверяем, есть ли товары в корзине
                    SELECT COUNT(*) INTO v_count
                    FROM main_basket
                    WHERE user_id = p_user_id;

                    IF v_count = 0 THEN
                        RAISE EXCEPTION 'Корзина пуста';
                    END IF;

                    -- Считаем общую сумму
                    SELECT COALESCE(SUM(b.quantity * p.price), 0)
                    INTO v_total
                    FROM main_basket b
                    JOIN main_product p ON b.product_id = p.id
                    WHERE b.user_id = p_user_id;

                    -- Создаём заказ с NOW() для created_at
                    INSERT INTO main_order (user_id, total_price, status, created_at)
                    VALUES (p_user_id, v_total, 'pending', NOW())
                    RETURNING id INTO v_new_order_id;

                    -- Добавляем элементы заказа
                    INSERT INTO main_orderitem (order_id, product_id, quantity, price)
                    SELECT v_new_order_id, b.product_id, b.quantity, p.price
                    FROM main_basket b
                    JOIN main_product p ON b.product_id = p.id
                    WHERE b.user_id = p_user_id;

                    -- Очищаем корзину
                    DELETE FROM main_basket WHERE user_id = p_user_id;

                    RAISE NOTICE 'Заказ % создан для пользователя %', v_new_order_id, p_user_id;
                END;
                $$;

                -- 2. Процедура: применить скидку к товару
                CREATE OR REPLACE PROCEDURE apply_discount_to_product(IN product_id INT, IN discount_percent INT)
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    current_price DECIMAL(10,2);
                BEGIN
                    IF discount_percent < 0 OR discount_percent > 100 THEN
                        RAISE EXCEPTION 'Скидка должна быть от 0 до 100%%';
                    END IF;

                    SELECT price INTO current_price
                    FROM main_product
                    WHERE id = product_id;

                    IF current_price IS NULL THEN
                        RAISE EXCEPTION 'Товар не найден';
                    END IF;

                    UPDATE main_product
                    SET
                        old_price = price,
                        price = ROUND(price * (100 - discount_percent) / 100, 2),
                        discount = discount_percent
                    WHERE id = product_id;

                    RAISE NOTICE 'Скидка %%% применена к товару %', discount_percent, product_id;
                END;
                $$;

                -- 3. Процедура: удалить товары из корзины и вишлиста, которых больше нет в каталоге
                CREATE OR REPLACE PROCEDURE cleanup_orphaned_items()
                LANGUAGE plpgsql
                AS $$
                DECLARE
                    basket_count INT;
                    wishlist_count INT;
                BEGIN
                    SELECT COUNT(*) INTO basket_count
                    FROM main_basket b
                    LEFT JOIN main_product p ON b.product_id = p.id
                    WHERE p.id IS NULL;

                    SELECT COUNT(*) INTO wishlist_count
                    FROM main_wishlist w
                    LEFT JOIN main_product p ON w.product_id = p.id
                    WHERE p.id IS NULL;

                    DELETE FROM main_basket
                    WHERE product_id NOT IN (SELECT id FROM main_product);

                    DELETE FROM main_wishlist
                    WHERE product_id NOT IN (SELECT id FROM main_product);

                    RAISE NOTICE 'Очистка завершена: удалено % товаров из корзин и % из списков желаний', basket_count, wishlist_count;
                END;
                $$;
                 -- 4. Пересчёт средних рейтингов товаров
                CREATE OR REPLACE PROCEDURE recalculate_product_ratings()
                LANGUAGE plpgsql
                AS $$
                BEGIN
                    UPDATE main_product
                    SET average_rating = COALESCE((
                        SELECT ROUND(AVG(rating), 2)
                        FROM main_review
                        WHERE main_review.product_id = main_product.id
                    ), 0.00);

                    RAISE NOTICE 'Средние рейтинги для всех товаров успешно пересчитаны.';
                END;
                $$;
                """,
            reverse_sql="""
                DROP PROCEDURE IF EXISTS create_order_from_basket(INT);
                DROP PROCEDURE IF EXISTS apply_discount_to_product(INT, INT);
                DROP PROCEDURE IF EXISTS cleanup_orphaned_items();
                DROP PROCEDURE IF EXISTS recalculate_product_ratings();
                """
        ),

        # 🔹 ПРЕДСТАВЛЕНИЯ (без is_archived!)
        migrations.RunSQL(
            sql="""
                -- 1. Представление: активные заказы с деталями (без is_archived)
                CREATE OR REPLACE VIEW active_orders_view AS
                SELECT
                    o.id AS order_id,
                    o.created_at,
                    o.status,
                    u.username AS user_name,
                    u.email AS user_email,
                    SUM(oi.quantity * oi.price) AS total,
                    COUNT(oi.id) AS items_count
                FROM main_order o
                JOIN auth_user u ON o.user_id = u.id
                JOIN main_orderitem oi ON o.id = oi.order_id
                WHERE o.status != 'cancelled'
                GROUP BY o.id, o.created_at, o.status, u.username, u.email;

                -- 2. Представление: топ-5 самых продаваемых товаров
                CREATE OR REPLACE VIEW top_selling_products_view AS
                SELECT
                    p.id,
                    p.name,
                    p.game_id,
                    g.name AS game_name,
                    SUM(oi.quantity) AS total_sold,
                    COUNT(DISTINCT o.id) AS orders_count
                FROM main_product p
                JOIN main_orderitem oi ON p.id = oi.product_id
                JOIN main_order o ON oi.order_id = o.id
                JOIN main_game g ON p.game_id = g.id
                WHERE o.status = 'completed'
                GROUP BY p.id, p.name, p.game_id, g.name
                ORDER BY total_sold DESC
                LIMIT 5;

                -- 3. Представление: пользователи с наибольшим количеством желаний
                CREATE OR REPLACE VIEW top_wishlists_view AS
                SELECT
                    u.id AS user_id,
                    u.username,
                    u.email,
                    COUNT(w.id) AS wishlist_count
                FROM auth_user u
                LEFT JOIN main_wishlist w ON u.id = w.user_id
                GROUP BY u.id, u.username, u.email
                ORDER BY wishlist_count DESC
                LIMIT 10;
                """,
            reverse_sql="""
                DROP VIEW IF EXISTS active_orders_view;
                DROP VIEW IF EXISTS top_selling_products_view;
                DROP VIEW IF EXISTS top_wishlists_view;
                """
        ),
    ]
