# Generated by Django 5.2.3 on 2026-02-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('на рассмотрении', 'На рассмотрении'), ('доставлен', 'Доставлен'), ('отменён', 'Отменён')], default='на рассмотрении', max_length=50),
        ),
    ]
