# Generated by Django 5.2.3 on 2026-02-08 12:41

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.game_logo_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.product_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
    ]
